name: Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GHP_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2.0.1
      with:
        bun-version: latest
    - run: bun i && bun run build
    - uses: actions/configure-pages@v4
    - uses: actions/upload-pages-artifact@v3
      with:
        path: 'dist'
    - id: deployment
      uses: actions/deploy-pages@v4
